import { CapPlanningItem } from '../../models/capplanningitem.model';

export const capPlanningItems: CapPlanningItem[] = [
  {
    id: 1,
    capGroupId: 1,
    capGroup: {
      id: 1,
      capGroup: '1H201',
      capTypeId: 1,
      capType: {
        id: 1,
        capType: 'Fröccsöntő',
        companyId: 1,
        plantId: 1,
      },
      capName: 'Engel 1',
      capUnitId: 1,
      capUnit: {
        id: 1,
        unit: 'h',
        name: 'óra',
        companyId: 1,
        plantId: 1,
      },
    },
    companyId: 1,
    plantId: 1,
    year: 2021,
    p1: 0,
    p2: 0,
    p3: 0,
    p4: 0,
    p5: 0,
    p6: 0,
    p7: 0,
    p8: 0,
    p9: 0,
    p10: 0,
    p11: 0,
    p12: 0,
  },
  {
    id: 2,
    capGroupId: 1,
    capGroup: {
      id: 1,
      capGroup: '1H201',
      capTypeId: 1,
      capType: {
        id: 1,
        capType: 'Fröccsöntő',
        companyId: 1,
        plantId: 1,
      },
      capName: 'Engel 1',
      capUnitId: 1,
      capUnit: {
        id: 1,
        unit: 'h',
        name: 'óra',
        companyId: 1,
        plantId: 1,
      },
    },
    companyId: 1,
    plantId: 1,
    year: 2022,
    p1: 0,
    p2: 0,
    p3: 0,
    p4: 0,
    p5: 0,
    p6: 0,
    p7: 0,
    p8: 0,
    p9: 0,
    p10: 0,
    p11: 0,
    p12: 0,
  },
];
