import { ProvkDetail } from '../../models/provkdetail.model';

export const provkDetails: ProvkDetail[] = [
  {
    id: 1,
    provkId: 1,
    year: 2021,
    month: 1,
    version: 1,
    capGroupId: 1,
    value: 100,
    capGroup: {
      id: 1,
      capGroup: '1H201',
      capTypeId: 1,
      capName: 'Engel 1',
      capUnitId: 1,
      capUnit: {
        id: 1,
        unit: 'h',
        name: 'óra',
        companyId: 1,
        plantId: 1,
      },
      invNr: '335233',
      normalCap: 5365,
      fixRate: 85.15,
      capYear: 2021,
      capYearDate: new Date(2021, 0, 1),
      companyId: 1,
      plantId: 1,
    },
    ba: 0,
  },
  {
    id: 2,
    provkId: 1,
    year: 2021,
    month: 1,
    version: 1,
    capGroupId: 2,
    value: 200,
    capGroup: {
      id: 2,
      capGroup: '1H2K10',
      capTypeId: 3,
      capName: 'AU326 LDM',
      capUnitId: 2,
      capUnit: {
        id: 2,
        unit: 'db',
        name: 'darab',
        companyId: 1,
        plantId: 1,
      },
      invNr: 'K10',
      normalCap: 561760,
      fixRate: 0.66,
      capYear: 2021,
      capYearDate: new Date(2021, 0, 1),
      companyId: 1,
      plantId: 1,
    },
    ba: 0,
  },
  {
    id: 3,
    provkId: 1,
    year: 2021,
    month: 1,
    version: 1,
    capGroupId: 3,
    value: 100,
    capGroup: {
      id: 3,
      capGroup: '1H202',
      capTypeId: 1,
      capName: 'Engel 2',
      capUnitId: 1,
      capUnit: {
        id: 1,
        unit: 'h',
        name: 'óra',
        companyId: 1,
        plantId: 1,
      },
      invNr: '337111',
      normalCap: 5365,
      fixRate: 85.15,
      capYear: 2021,
      capYearDate: new Date(2021, 0, 1),
      companyId: 1,
      plantId: 1,
    },
    ba: 0,
  },
];
