import { Frc } from '../../models/frc.model';

export const frcs: Frc[] = [
  {
    id: 1,
    companyId: 1,
    plantId: 1,
    year: 2021,
    costAccTypeId: 2,
    costAccType: {
      descr: 'Budget tervezés',
      id: 2,
      name: 'Budget',
    },
    hovered: false,
    plant: {
      id: 1,
      code: '1H0',
    },
    company: {
      id: 1,
      name: 'company 1 long name',
      shortName: 'company short name',
    },
    version: '0+12',
    va: -100,
    ba: -300,
  },
  {
    id: 2,
    companyId: 1,
    plantId: 1,
    year: 2021,
    costAccTypeId: 2,
    costAccType: {
      descr: 'Budget tervezés',
      id: 2,
      name: 'Budget',
    },
    hovered: false,
    plant: {
      id: 1,
      code: '1H0',
    },
    company: {
      id: 1,
      name: 'company 1 long name',
      shortName: 'company short name',
    },
    version: '1+11',
    va: -100,
    ba: -300,
  },
  {
    id: 3,
    companyId: 1,
    plantId: 1,
    year: 2021,
    costAccTypeId: 2,
    costAccType: {
      descr: 'Budget tervezés',
      id: 2,
      name: 'Budget',
    },
    hovered: false,
    plant: {
      id: 1,
      code: '1H0',
    },
    company: {
      id: 1,
      name: 'company 1 long name',
      shortName: 'company short name',
    },
    version: '2+10',
    va: -100,
    ba: -300,
  },
  {
    id: 4,
    companyId: 1,
    plantId: 1,
    year: 2021,
    costAccTypeId: 2,
    costAccType: {
      descr: 'Budget tervezés',
      id: 2,
      name: 'Budget',
    },
    hovered: false,
    plant: {
      id: 1,
      code: '1H0',
    },
    company: {
      id: 1,
      name: 'company 1 long name',
      shortName: 'company short name',
    },
    version: '3+9',
    va: -100,
    ba: -300,
  },
  {
    id: 5,
    companyId: 1,
    plantId: 1,
    year: 2021,
    costAccTypeId: 2,
    costAccType: {
      descr: 'Budget tervezés',
      id: 2,
      name: 'Budget',
    },
    hovered: false,
    plant: {
      id: 1,
      code: '1H0',
    },
    company: {
      id: 1,
      name: 'company 1 long name',
      shortName: 'company short name',
    },
    version: '4+8',
    va: -100,
    ba: -300,
  },
  {
    id: 6,
    companyId: 1,
    plantId: 1,
    year: 2021,
    costAccTypeId: 2,
    costAccType: {
      descr: 'Budget tervezés',
      id: 2,
      name: 'Budget',
    },
    hovered: false,
    plant: {
      id: 1,
      code: '1H0',
    },
    company: {
      id: 1,
      name: 'company 1 long name',
      shortName: 'company short name',
    },
    version: '5+7',
    va: -100,
    ba: -300,
  },
  {
    id: 7,
    companyId: 1,
    plantId: 1,
    year: 2021,
    costAccTypeId: 2,
    costAccType: {
      descr: 'Budget tervezés',
      id: 2,
      name: 'Budget',
    },
    hovered: false,
    plant: {
      id: 1,
      code: '1H0',
    },
    company: {
      id: 1,
      name: 'company 1 long name',
      shortName: 'company short name',
    },
    version: '6+6',
    va: -100,
    ba: -300,
  },
  {
    id: 8,
    companyId: 1,
    plantId: 1,
    year: 2021,
    costAccTypeId: 2,
    costAccType: {
      descr: 'Budget tervezés',
      id: 2,
      name: 'Budget',
    },
    hovered: false,
    plant: {
      id: 1,
      code: '1H0',
    },
    company: {
      id: 1,
      name: 'company 1 long name',
      shortName: 'company short name',
    },
    version: '7+5',
    va: -100,
    ba: -300,
  },
  {
    id: 9,
    companyId: 1,
    plantId: 1,
    year: 2021,
    costAccTypeId: 2,
    costAccType: {
      descr: 'Budget tervezés',
      id: 2,
      name: 'Budget',
    },
    hovered: false,
    plant: {
      id: 1,
      code: '1H0',
    },
    company: {
      id: 1,
      name: 'company 1 long name',
      shortName: 'company short name',
    },
    version: '8+4',
    va: -100,
    ba: -300,
  },
  {
    id: 10,
    companyId: 1,
    plantId: 1,
    year: 2021,
    costAccTypeId: 2,
    costAccType: {
      descr: 'Budget tervezés',
      id: 2,
      name: 'Budget',
    },
    hovered: false,
    plant: {
      id: 1,
      code: '1H0',
    },
    company: {
      id: 1,
      name: 'company 1 long name',
      shortName: 'company short name',
    },
    version: '9+3',
    va: -100,
    ba: -300,
  },
  {
    id: 11,
    companyId: 1,
    plantId: 1,
    year: 2021,
    costAccTypeId: 2,
    costAccType: {
      descr: 'Budget tervezés',
      id: 2,
      name: 'Budget',
    },
    hovered: false,
    plant: {
      id: 1,
      code: '1H0',
    },
    company: {
      id: 1,
      name: 'company 1 long name',
      shortName: 'company short name',
    },
    version: '10+2',
    va: -100,
    ba: -300,
  },
  {
    id: 12,
    companyId: 1,
    plantId: 1,
    year: 2021,
    costAccTypeId: 2,
    costAccType: {
      descr: 'Budget tervezés',
      id: 2,
      name: 'Budget',
    },
    hovered: false,
    plant: {
      id: 1,
      code: '1H0',
    },
    company: {
      id: 1,
      name: 'company 1 long name',
      shortName: 'company short name',
    },
    version: '11+1',
    va: -100,
    ba: -300,
  },
];
