import { CapGroup } from '../../models/capgroup.model';

export const capGroups: CapGroup[] = [
  {
    id: 1,
    capGroup: '1H201',
    capTypeId: 1,
    capType: {
      id: 1,
      capType: 'Fröccsöntő',
      companyId: 1,
      plantId: 1,
    },
    capName: 'Engel 1',
    capUnitId: 1,
    capUnit: {
      id: 1,
      unit: 'h',
      name: 'óra',
      companyId: 1,
      company: {
        id: 1,
        name: 'company 1 long name',
        shortName: 'company 1',
      },
      plantId: 1,
      plant: {
        id: 1,
        code: '1H0',
      },
    },
    invNr: '335233',
    normalCap: 5365,
    fixRate: 85.15,
    capYear: 2021,
    capYearDate: new Date(2021, 0, 1),
    companyId: 1,
    company: {
      id: 1,
      name: 'company 1 long name',
      shortName: 'company 1',
    },
    plantId: 1,
    plant: {
      id: 1,
      code: '1H0',
    },
  },
  {
    id: 2,
    capGroup: '1H2K10',
    capTypeId: 3,
    capType: {
      id: 3,
      capType: 'Szerelde',
      companyId: 1,
      plantId: 1,
    },
    capName: 'AU326 LDM',
    capUnitId: 2,
    capUnit: {
      id: 2,
      unit: 'db',
      name: 'darab',
      companyId: 1,
      company: {
        id: 1,
        name: 'company 1 long name',
        shortName: 'company 1',
      },
      plantId: 1,
      plant: {
        id: 1,
        code: '1H0',
      },
    },
    invNr: 'K10',
    normalCap: 561760,
    fixRate: 0.66,
    capYear: 2021,
    capYearDate: new Date(2021, 0, 1),
    companyId: 1,
    company: {
      id: 1,
      name: 'company 1 long name',
      shortName: 'company 1',
    },
    plantId: 1,
    plant: {
      id: 1,
      code: '1H0',
    },
  },
  {
    id: 3,
    capGroup: '1H202',
    capTypeId: 1,
    capType: {
      id: 1,
      capType: 'Fröccsöntő',
      companyId: 1,
      plantId: 1,
    },
    capName: 'Engel 2',
    capUnitId: 1,
    capUnit: {
      id: 1,
      unit: 'h',
      name: 'óra',
      companyId: 1,
      company: {
        id: 1,
        name: 'company 1 long name',
        shortName: 'company 1',
      },
      plantId: 1,
      plant: {
        id: 1,
        code: '1H0',
      },
    },
    invNr: '337111',
    normalCap: 5365,
    fixRate: 85.15,
    capYear: 2021,
    capYearDate: new Date(2021, 0, 1),
    companyId: 1,
    company: {
      id: 1,
      name: 'company 1 long name',
      shortName: 'company 1',
    },
    plantId: 1,
    plant: {
      id: 1,
      code: '1H0',
    },
  },
];
