import { FrcSalesProduct } from '../../models/frc-salesproduct.model';

export const frcSalesProductItems: FrcSalesProduct[] = [
  {
    id: 1,
    frcId: 1,
    salesProductid: 1,
    salesProduct: {
      id: 1,
      name: 'AU536PA BMP',
      unitId: 2,
      unit: {
        id: 2,
        unit: 'db',
        name: 'darab',
        companyId: 1,
        plantId: 1,
      },
    },
    p1: 10,
    p2: 20,
    p3: 30,
    p4: 40,
    p5: 50,
    p6: 0,
    p7: 0,
    p8: 0,
    p9: 0,
    p10: 0,
    p11: 0,
    p12: 0,
    total: 150,
  },
  {
    id: 2,
    frcId: 1,
    salesProductid: 2,
    salesProduct: {
      id: 2,
      name: 'AU326 LDM',
      capGroupId: 2,
      capGroup: {
        id: 2,
        capGroup: '1H2K10',
        capTypeId: 3,
        capName: 'AU326 LDM',
        capType: {
          id: 3,
          capType: 'Szerelde',
          companyId: 1,
          plantId: 1,
        },
      },
      unitId: 2,
      unit: {
        id: 2,
        unit: 'db',
        name: 'darab',
      },
    },
    p1: 10,
    p2: 20,
    p3: 0,
    p4: 0,
    p5: 0,
    p6: 0,
    p7: 0,
    p8: 0,
    p9: 0,
    p10: 0,
    p11: 0,
    p12: 0,
    total: 30,
  },
];
