import { HcPlanningItem } from '../../models/hcplanningitem.model';

export const hcPlanningItems: HcPlanningItem[] = [
  {
    id: 1,
    companyId: 1,
    company: { id: 1, name: 'company 1 long name', shortName: 'company 1' },
    year: 2021,
    plantId: 1,
    plant: { id: 1, code: '1H0' },
    costAccTypeId: 2,
    costAccType: { id: 2, name: 'Budget', descr: 'Budget tervezés' },
    costCenterId: 1,
    costCenter: { id: 1, code: '1H3300', name: 'Szerelde' },
    costGroupId: 3,
    costGroup: {
      id: 3,
      name: 'Operátori bérköltség',
      usedForPersPlanning: true,
    },
    jobId: 4,
    job: {
      id: 4,
      name: 'Operátor',
      depId: 3,
      department: {
        id: 3,
        name: 'Szerelde',
      },
    },
    comment: 'some comment',
    p1: 210,
    p2: 210,
    p3: 210,
    p4: 210,
    p5: 210,
    p6: 210,
    p7: 210,
    p8: 210,
    p9: 210,
    p10: 210,
    p11: 210,
    p12: 210,
    costAssigned: true,
    taskId: 1,
    task: {
      id: 1,
      itemId: 1,
      type: 0,
      status: 0,
      year: 2021,
      task: 'feladat',
    },
  },
];
