import { FrcCapacity } from '../../models/frc-capacity.model';

export const frcCapacityItems: FrcCapacity[] = [
  {
    id: 1,
    frcId: 1,
    capGroupId: 1,
    capGroup: {
      id: 1,
      capGroup: '1H201',
      capTypeId: 1,
      capType: {
        id: 1,
        capType: 'Fröccsöntő',
        companyId: 1,
        plantId: 1,
      },
      capName: 'Engel 1',
      capUnitId: 1,
      capUnit: {
        id: 1,
        unit: 'h',
        name: 'óra',
        companyId: 1,
        plantId: 1,
      },
    },
    p1: 10,
    p2: 20,
    p3: 30,
    p4: 40,
    p5: 50,
    p6: 0,
    p7: 0,
    p8: 0,
    p9: 0,
    p10: 0,
    p11: 0,
    p12: 0,
    total: 150,
  },
  {
    id: 2,
    frcId: 1,
    capGroupId: 2,
    capGroup: {
      id: 2,
      capGroup: '1H2K10',
      capTypeId: 3,
      capType: {
        id: 3,
        capType: 'Szerelde',
        companyId: 1,
        plantId: 1,
      },
      capName: 'AU326 LDM',
      capUnitId: 2,
      capUnit: {
        id: 2,
        unit: 'db',
        name: 'darab',
        companyId: 1,
        plantId: 1,
      },
    },
    p1: 10,
    p2: 20,
    p3: 0,
    p4: 0,
    p5: 0,
    p6: 0,
    p7: 0,
    p8: 0,
    p9: 0,
    p10: 0,
    p11: 0,
    p12: 0,
    total: 30,
  },
];
