import { drawerItem } from './sidebar-item.type';

export const drawerItemsFlattened: drawerItem[] = [
  {
    text: 'sidebar.masterData',
    icon: 'file-data',
    expanded: false,
    parent: true,
    level: 0,
    id: '0',
    parentId: '',
    children: [],
    translateId: 'sidebar.masterData',
  },
  {
    text: 'sidebar.general',
    expanded: false,
    parent: true,
    level: 1,
    id: '0.1',
    parentId: '0',
    children: [],
    translateId: 'sidebar.general',
  },
  {
    text: 'sidebar.companies',
    level: 2,
    id: '0.1.1',
    parentId: '0.1',
    routePath: 'masterdata/general/company',
    translateId: 'sidebar.companies',
  },
  {
    text: 'sidebar.plants',
    level: 2,
    id: '0.1.2',
    parentId: '0.1',
    routePath: 'masterdata/general/plant',
    translateId: 'sidebar.plants',
  },
  {
    text: 'sidebar.plantAreas',
    level: 2,
    id: '0.1.3',
    parentId: '0.1',
    routePath: 'masterdata/general/plantarea',
    translateId: 'sidebar.plantAreas',
  },
  {
    text: 'sidebar.departments',
    level: 2,
    id: '0.1.4',
    parentId: '0.1',
    routePath: 'masterdata/general/department',
    translateId: 'sidebar.departments',
  },
  {
    text: 'sidebar.jobs',
    level: 2,
    id: '0.1.5',
    parentId: '0.1',
    routePath: 'masterdata/general/job',
    translateId: 'sidebar.jobs',
  },
  {
    text: 'sidebar.languages',
    level: 2,
    id: '0.1.6',
    parentId: '0.1',
    routePath: 'masterdata/general/language',
    translateId: 'sidebar.languages',
  },
  {
    text: 'sidebar.dictionary',
    level: 2,
    id: '0.1.7',
    parentId: '0.1',
    translateId: 'sidebar.dictionary',
  },
  {
    text: 'sidebar.planningAndSettlement',
    expanded: false,
    parent: true,
    level: 1,
    id: '0.2',
    parentId: '0',
    children: [],
    translateId: 'sidebar.planningAndSettlement',
  },
  {
    text: 'sidebar.costAccTypes',
    level: 2,
    id: '0.2.1',
    parentId: '0.2',
    routePath: 'masterdata/planning/costacctype',
    translateId: 'sidebar.costAccTypes',
  },
  {
    text: 'sidebar.costGroups',
    level: 2,
    id: '0.2.2',
    parentId: '0.2',
    routePath: 'masterdata/planning/costgroup',
    translateId: 'sidebar.costGroups',
  },
  {
    text: 'sidebar.costCenters',
    level: 2,
    id: '0.2.3',
    parentId: '0.2',
    routePath: 'masterdata/planning/costcenter',
    translateId: 'sidebar.costCenters',
  },
  {
    text: 'sidebar.costResponsibles',
    level: 2,
    id: '0.2.4',
    parentId: '0.2',
    routePath: 'masterdata/planning/costresp',
    translateId: 'sidebar.costResponsibles',
  },
  {
    text: 'sidebar.costAccounts',
    level: 2,
    id: '0.2.5',
    parentId: '0.2',
    routePath: 'masterdata/planning/costaccount',
    translateId: 'sidebar.costAccounts',
  },
  {
    text: 'sidebar.costAllocations',
    level: 2,
    id: '0.2.6',
    parentId: '0.2',
    routePath: 'masterdata/planning/costallocation',
    translateId: 'sidebar.costAllocations',
  },
  {
    text: 'sidebar.production',
    expanded: false,
    parent: true,
    level: 1,
    id: '0.3',
    parentId: '0',
    children: [],
    translateId: 'sidebar.production',
  },
  {
    text: 'sidebar.capGroups',
    level: 2,
    id: '0.3.1',
    parentId: '0.3',
    routePath: 'masterdata/production/capgroup',
    translateId: 'sidebar.capGroups',
  },
  {
    text: 'sidebar.salesProducts',
    level: 2,
    id: '0.3.2',
    parentId: '0.3',
    routePath: 'masterdata/production/salesproduct',
    translateId: 'sidebar.salesProducts',
  },
  {
    text: 'sidebar.capTypes',
    level: 2,
    id: '0.3.3',
    parentId: '0.3',
    routePath: 'masterdata/production/captype',
    translateId: 'sidebar.capTypes',
  },
  {
    text: 'sidebar.capUnits',
    level: 2,
    id: '0.3.4',
    parentId: '0.3',
    routePath: 'masterdata/production/capunit',
    translateId: 'sidebar.capUnits',
  },
  {
    text: 'sidebar.prodData',
    icon: 'wrench',
    expanded: false,
    parent: true,
    level: 0,
    id: '1',
    parentId: '',
    children: [],
    translateId: 'sidebar.prodData',
  },
  {
    text: 'sidebar.saveActualData',
    level: 1,
    id: '1.1',
    parentId: '1',
    routePath: 'productiondata/actual',
    translateId: 'sidebar.saveActualData',
  },
  {
    text: 'sidebar.forecasting',
    icon: 'graph',
    expanded: false,
    parent: true,
    level: 0,
    id: '2',
    parentId: '',
    children: [],
    translateId: 'sidebar.forecasting',
  },
  {
    text: 'sidebar.provk',
    level: 1,
    id: '2.1',
    parentId: '2',
    routePath: 'forecast/provk',
    translateId: 'sidebar.provk',
  },
  {
    text: 'sidebar.forecast',
    level: 1,
    id: '2.2',
    parentId: '2',
    routePath: 'forecast/frc',
    translateId: 'sidebar.forecast',
  },
  {
    text: 'sidebar.plantResult',
    icon: 'currency',
    expanded: false,
    parent: true,
    level: 0,
    id: '3',
    parentId: '',
    children: [],
    translateId: 'sidebar.plantResult',
  },
  {
    text: 'sidebar.uploadPlantCosts',
    level: 1,
    id: '3.1',
    parentId: '3',
    routePath: 'plantresult/uploadcost',
    translateId: 'sidebar.uploadPlantCosts',
  },
  {
    text: 'sidebar.browseBookings',
    level: 1,
    id: '3.3',
    parentId: '3',
    routePath: 'plantresult/browsedata',
    translateId: 'sidebar.browseBookings',
  },
  {
    text: 'sidebar.reports',
    level: 1,
    expanded: false,
    parent: true,
    id: '3.4',
    parentId: '3',
    children: [],
    translateId: 'sidebar.reports',
  },
  {
    text: 'sidebar.costOverview',
    level: 2,
    id: '3.4.1',
    parentId: '3.4',
    routePath: 'plantresult/costcenter',
    translateId: 'sidebar.costOverview',
  },
  {
    text: 'sidebar.plantPl',
    level: 2,
    id: '3.4.2',
    parentId: '3.4',
    routePath: 'plantresult/plantpl',
    translateId: 'sidebar.plantPl',
  },
  {
    text: 'sidebar.planning',
    icon: 'calendar',
    expanded: false,
    parent: true,
    level: 0,
    id: '4',
    parentId: '',
    children: [],
    translateId: 'sidebar.planning',
  },
  {
    text: 'sidebar.planningVersions',
    level: 1,
    id: '4.1',
    parentId: '4',
    routePath: 'planning/version',
    translateId: 'sidebar.planningVersions',
  },
  {
    text: 'sidebar.costPlanning',
    level: 1,
    id: '4.2',
    parentId: '4',
    routePath: 'planning/costplanning',
    translateId: 'sidebar.costPlanning',
  },
  {
    text: 'sidebar.hcPlanning',
    level: 1,
    id: '4.3',
    parentId: '4',
    routePath: 'planning/hcplanning',
    translateId: 'sidebar.hcPlanning',
  },
  {
    text: 'sidebar.capPlanning',
    level: 1,
    id: '4.4',
    parentId: '4',
    routePath: 'planning/capplanning',
    translateId: 'sidebar.capPlanning',
  },
];
