import { drawerItem } from './sidebar-item.type';

export const drawerItemsHierarchy: drawerItem[] = [
  {
    text: 'Törzsadatok',
    icon: 'file-data',
    selected: false,
    expanded: false,
    parent: true,
    level: 0,
    id: '0',
    parentId: '',
    children: [
      {
        text: 'Általános',
        selected: false,
        expanded: false,
        parent: true,
        level: 1,
        id: '0.1',
        parentId: '0',
        children: [
          {
            text: 'Gazdasági egységek',
            level: 2,
            id: '0.1.1',
            parentId: '0.1',
            routePath: 'masterdata/general/company',
          },
          {
            text: 'Gyárak',
            level: 2,
            id: '0.1.2',
            parentId: '0.1',
            routePath: 'masterdata/general/plant',
          },
          {
            text: 'Gyáregységek',
            level: 2,
            id: '0.1.3',
            parentId: '0.1',
            routePath: 'masterdata/general/plantarea',
          },
          {
            text: 'Részlegek',
            level: 2,
            id: '0.1.4',
            parentId: '0.1',
            routePath: 'masterdata/general/department',
          },
          {
            text: 'Munkakörök',
            level: 2,
            id: '0.1.5',
            parentId: '0.1',
            routePath: 'masterdata/general/job',
          },
          {
            text: 'Nyelvek',
            level: 2,
            id: '0.1.6',
            parentId: '0.1',
            routePath: 'masterdata/general/language',
          },
          {
            text: 'Szótár',
            level: 2,
            id: '0.1.7',
            parentId: '0.1',
          },
        ],
      },
      {
        text: 'Tervezés és elszámolás',
        selected: false,
        expanded: false,
        parent: true,
        level: 1,
        id: '0.2',
        parentId: '0',
        children: [
          {
            text: 'Költségszámítási típusok',
            level: 2,
            id: '0.2.1',
            parentId: '0.2',
            routePath: 'masterdata/planning/costacctype',
          },
          {
            text: 'Költségcsoportok',
            level: 2,
            id: '0.2.2',
            parentId: '0.2',
            routePath: 'masterdata/planning/costgroup',
          },
          {
            text: 'Költséghelyek',
            level: 2,
            id: '0.2.3',
            parentId: '0.2',
            routePath: 'masterdata/planning/costcenter',
          },
          {
            text: 'Költségfelelősök',
            level: 2,
            id: '0.2.4',
            parentId: '0.2',
            routePath: 'masterdata/planning/costresp',
          },
          {
            text: 'Költségnemek',
            level: 2,
            id: '0.2.5',
            parentId: '0.2',
            routePath: 'masterdata/planning/costaccount',
          },
          {
            text: 'Költségátterhelések',
            level: 2,
            id: '0.2.6',
            parentId: '0.2',
            routePath: 'masterdata/planning/costallocation',
          },
        ],
      },
      {
        text: 'Termelés',
        selected: false,
        expanded: false,
        parent: true,
        level: 1,
        id: '0.3',
        parentId: '0',
        children: [
          {
            text: 'Kapacitáscsoportok',
            level: 2,
            id: '0.3.1',
            parentId: '0.3',
            routePath: 'masterdata/production/capgroup',
          },
          {
            text: 'Értékesített termékek',
            level: 2,
            id: '0.3.2',
            parentId: '0.3',
            routePath: 'masterdata/production/salesproduct',
          },
          {
            text: 'Kapacitástípusok',
            level: 2,
            id: '0.3.3',
            parentId: '0.3',
            routePath: 'masterdata/production/captype',
          },
          {
            text: 'Kapacitásegységek',
            level: 2,
            id: '0.3.4',
            parentId: '0.3',
            routePath: 'masterdata/production/capunit',
          },
        ],
      },
    ],
  },
  {
    text: 'Termelési adatok',
    icon: 'wrench',
    expanded: false,
    selected: false,
    parent: true,
    level: 0,
    id: '1',
    parentId: '',
    children: [
      {
        text: 'Tény adatok rögzítése',
        level: 1,
        id: '1.1',
        parentId: '1',
        routePath: 'productiondata/actual',
      },
    ],
  },
  {
    text: 'Előrejelzés',
    icon: 'graph',
    selected: false,
    expanded: false,
    parent: true,
    level: 0,
    id: '2',
    parentId: '',
    children: [
      {
        text: 'PROVK',
        level: 1,
        id: '2.1',
        parentId: '2',
        routePath: 'forecast/provk',
      },
      {
        text: 'Forecast',
        level: 1,
        id: '2.2',
        parentId: '2',
        routePath: 'forecast/frc',
      },
    ],
  },
  {
    text: 'Gyári eredmény',
    icon: 'currency',
    selected: false,
    expanded: false,
    parent: true,
    level: 0,
    id: '3',
    parentId: '',
    children: [
      {
        text: 'Gyári költségek feltöltése',
        level: 1,
        id: '3.1',
        parentId: '3',
        routePath: 'plantresult/uploadcost',
      },
      {
        text: 'Könyvelési adatok tallózása',
        level: 1,
        id: '3.3',
        parentId: '3',
        routePath: 'plantresult/browsedata',
      },
      {
        text: 'Kimutatások',
        level: 1,
        selected: false,
        expanded: false,
        parent: true,
        id: '3.4',
        parentId: '3',
        children: [
          {
            text: 'Költséghelyi áttekintő',
            level: 2,
            id: '3.4.1',
            parentId: '3.4',
            routePath: 'plantresult/costcenter',
          },
          {
            text: 'Gyári eredménykimutatás',
            level: 2,
            id: '3.4.2',
            parentId: '3.4',
            routePath: 'plantresult/plantpl',
          },
        ],
      },
    ],
  },
  {
    text: 'Tervezés',
    icon: 'calendar',
    selected: false,
    expanded: false,
    parent: true,
    level: 0,
    id: '4',
    parentId: '',
    children: [
      {
        text: 'Tervverziók',
        level: 1,
        id: '4.1',
        parentId: '4',
        routePath: 'planning/version',
      },
      {
        text: 'Költségtervezés',
        level: 1,
        id: '4.2',
        parentId: '4',
        routePath: 'planning/costplanning',
      },
      {
        text: 'Létszámtervezés',
        level: 1,
        id: '4.3',
        parentId: '4',
        routePath: 'planning/hcplanning',
      },
      {
        text: 'Kapacitástervezés',
        level: 1,
        id: '4.4',
        parentId: '4',
        routePath: 'planning/capplanning',
      },
    ],
  },
];
