import { drawerItem } from './sidebar-item.type';

export const drawerItemsFlattened: drawerItem[] = [
  {
    text: 'sidebar.masterData',
    icon: 'file-data',
    expanded: false,
    parent: true,
    level: 0,
    id: '0',
    parentId: '',
    children: [],
  },
  {
    text: 'sidebar.general',
    expanded: false,
    parent: true,
    level: 1,
    id: '0.1',
    parentId: '0',
    children: [],
  },
  {
    text: 'sidebar.companies',
    level: 2,
    id: '0.1.1',
    parentId: '0.1',
    routePath: 'masterdata/general/company',
  },
  {
    text: 'sidebar.plants',
    level: 2,
    id: '0.1.2',
    parentId: '0.1',
    routePath: 'masterdata/general/plant',
  },
  {
    text: 'sidebar.plantAreas',
    level: 2,
    id: '0.1.3',
    parentId: '0.1',
    routePath: 'masterdata/general/plantarea',
  },
  {
    text: 'sidebar.departments',
    level: 2,
    id: '0.1.4',
    parentId: '0.1',
    routePath: 'masterdata/general/department',
  },
  {
    text: 'sidebar.jobs',
    level: 2,
    id: '0.1.5',
    parentId: '0.1',
    routePath: 'masterdata/general/job',
  },
  {
    text: 'sidebar.languages',
    level: 2,
    id: '0.1.6',
    parentId: '0.1',
    routePath: 'masterdata/general/language',
  },
  {
    text: 'sidebar.dictionary',
    level: 2,
    id: '0.1.7',
    parentId: '0.1',
  },
  {
    text: 'sidebar.planningAndSettlement',
    expanded: false,
    parent: true,
    level: 1,
    id: '0.2',
    parentId: '0',
    children: [],
  },
  {
    text: 'sidebar.costAccTypes',
    level: 2,
    id: '0.2.1',
    parentId: '0.2',
    routePath: 'masterdata/planning/costacctype',
  },
  {
    text: 'sidebar.costGroups',
    level: 2,
    id: '0.2.2',
    parentId: '0.2',
    routePath: 'masterdata/planning/costgroup',
  },
  {
    text: 'sidebar.costCenters',
    level: 2,
    id: '0.2.3',
    parentId: '0.2',
    routePath: 'masterdata/planning/costcenter',
  },
  {
    text: 'sidebar.costResponsibles',
    level: 2,
    id: '0.2.4',
    parentId: '0.2',
    routePath: 'masterdata/planning/costresp',
  },
  {
    text: 'sidebar.costAccounts',
    level: 2,
    id: '0.2.5',
    parentId: '0.2',
    routePath: 'masterdata/planning/costaccount',
  },
  {
    text: 'sidebar.costAllocations',
    level: 2,
    id: '0.2.6',
    parentId: '0.2',
    routePath: 'masterdata/planning/costallocation',
  },
  {
    text: 'sidebar.production',
    expanded: false,
    parent: true,
    level: 1,
    id: '0.3',
    parentId: '0',
    children: [],
  },
  {
    text: 'sidebar.capGroups',
    level: 2,
    id: '0.3.1',
    parentId: '0.3',
    routePath: 'masterdata/production/capgroup',
  },
  {
    text: 'sidebar.salesProducts',
    level: 2,
    id: '0.3.2',
    parentId: '0.3',
    routePath: 'masterdata/production/salesproduct',
  },
  {
    text: 'sidebar.capTypes',
    level: 2,
    id: '0.3.3',
    parentId: '0.3',
    routePath: 'masterdata/production/captype',
  },
  {
    text: 'sidebar.capUnits',
    level: 2,
    id: '0.3.4',
    parentId: '0.3',
    routePath: 'masterdata/production/capunit',
  },
  {
    text: 'sidebar.prodData',
    icon: 'wrench',
    expanded: false,
    parent: true,
    level: 0,
    id: '1',
    parentId: '',
    children: [],
  },
  {
    text: 'sidebar.saveActualData',
    level: 1,
    id: '1.1',
    parentId: '1',
    routePath: 'productiondata/actual',
  },
  {
    text: 'sidebar.forecasting',
    icon: 'graph',
    expanded: false,
    parent: true,
    level: 0,
    id: '2',
    parentId: '',
    children: [],
  },
  {
    text: 'sidebar.provk',
    level: 1,
    id: '2.1',
    parentId: '2',
    routePath: 'forecast/provk',
  },
  {
    text: 'sidebar.forecast',
    level: 1,
    id: '2.2',
    parentId: '2',
    routePath: 'forecast/frc',
  },
  {
    text: 'sidebar.plantResult',
    icon: 'currency',
    expanded: false,
    parent: true,
    level: 0,
    id: '3',
    parentId: '',
    children: [],
  },
  {
    text: 'sidebar.uploadPlantCosts',
    level: 1,
    id: '3.1',
    parentId: '3',
    routePath: 'plantresult/uploadcost',
  },
  {
    text: 'sidebar.browseBookings',
    level: 1,
    id: '3.3',
    parentId: '3',
    routePath: 'plantresult/browsedata',
  },
  {
    text: 'sidebar.reports',
    level: 1,
    expanded: false,
    parent: true,
    id: '3.4',
    parentId: '3',
    children: [],
  },
  {
    text: 'sidebar.costOverview',
    level: 2,
    id: '3.4.1',
    parentId: '3.4',
    routePath: 'plantresult/costcenter',
  },
  {
    text: 'sidebar.plantPl',
    level: 2,
    id: '3.4.2',
    parentId: '3.4',
    routePath: 'plantresult/plantpl',
  },
  {
    text: 'sidebar.planning',
    icon: 'calendar',
    expanded: false,
    parent: true,
    level: 0,
    id: '4',
    parentId: '',
    children: [],
  },
  {
    text: 'sidebar.planningVersions',
    level: 1,
    id: '4.1',
    parentId: '4',
    routePath: 'planning/version',
  },
  {
    text: 'sidebar.costPlanning',
    level: 1,
    id: '4.2',
    parentId: '4',
    routePath: 'planning/costplanning',
  },
  {
    text: 'sidebar.hcPlanning',
    level: 1,
    id: '4.3',
    parentId: '4',
    routePath: 'planning/hcplanning',
  },
  {
    text: 'sidebar.capPlanning',
    level: 1,
    id: '4.4',
    parentId: '4',
    routePath: 'planning/capplanning',
  },
];
