import { Provk } from '../../models/provk.model';

export const provks: Provk[] = [
  {
    id: 1,
    companyId: 1,
    plantId: 1,
    year: 2021,
    month: 1,
    versions: 3,
    hovered: false,
    plant: {
      id: 1,
      code: '1H0',
    },
    company: {
      id: 1,
      name: 'company 1 long name',
      shortName: 'company short name',
    },
  },
  {
    id: 2,
    companyId: 1,
    plantId: 1,
    year: 2021,
    month: 2,
    versions: 3,
    hovered: false,
    plant: {
      id: 1,
      code: '1H0',
    },
    company: {
      id: 1,
      name: 'company 1 long name',
      shortName: 'company short name',
    },
  },
  {
    id: 3,
    companyId: 1,
    plantId: 1,
    year: 2021,
    month: 3,
    versions: 3,
    hovered: false,
    plant: {
      id: 1,
      code: '1H0',
    },
    company: {
      id: 1,
      name: 'company 1 long name',
      shortName: 'company short name',
    },
  },
  {
    id: 4,
    companyId: 1,
    plantId: 1,
    year: 2021,
    month: 4,
    versions: 3,
    hovered: false,
    plant: {
      id: 1,
      code: '1H0',
    },
    company: {
      id: 1,
      name: 'company 1 long name',
      shortName: 'company short name',
    },
  },
  {
    id: 5,
    companyId: 1,
    plantId: 1,
    year: 2021,
    month: 5,
    versions: 3,
    hovered: false,
    plant: {
      id: 1,
      code: '1H0',
    },
    company: {
      id: 1,
      name: 'company 1 long name',
      shortName: 'company short name',
    },
  },
  {
    id: 6,
    companyId: 1,
    plantId: 1,
    year: 2021,
    month: 6,
    versions: 3,
    hovered: false,
    plant: {
      id: 1,
      code: '1H0',
    },
    company: {
      id: 1,
      name: 'company 1 long name',
      shortName: 'company short name',
    },
  },
  {
    id: 7,
    companyId: 1,
    plantId: 1,
    year: 2021,
    month: 7,
    versions: 3,
    hovered: false,
    plant: {
      id: 1,
      code: '1H0',
    },
    company: {
      id: 1,
      name: 'company 1 long name',
      shortName: 'company short name',
    },
  },
  {
    id: 8,
    companyId: 1,
    plantId: 1,
    year: 2021,
    month: 8,
    versions: 3,
    hovered: false,
    plant: {
      id: 1,
      code: '1H0',
    },
    company: {
      id: 1,
      name: 'company 1 long name',
      shortName: 'company short name',
    },
  },
  {
    id: 9,
    companyId: 1,
    plantId: 1,
    year: 2021,
    month: 9,
    versions: 3,
    hovered: false,
    plant: {
      id: 1,
      code: '1H0',
    },
    company: {
      id: 1,
      name: 'company 1 long name',
      shortName: 'company short name',
    },
  },
  {
    id: 10,
    companyId: 1,
    plantId: 1,
    year: 2021,
    month: 10,
    versions: 3,
    hovered: false,
    plant: {
      id: 1,
      code: '1H0',
    },
    company: {
      id: 1,
      name: 'company 1 long name',
      shortName: 'company short name',
    },
  },
  {
    id: 11,
    companyId: 1,
    plantId: 1,
    year: 2021,
    month: 11,
    versions: 3,
    hovered: false,
    plant: {
      id: 1,
      code: '1H0',
    },
    company: {
      id: 1,
      name: 'company 1 long name',
      shortName: 'company short name',
    },
  },
  {
    id: 12,
    companyId: 1,
    plantId: 1,
    year: 2021,
    month: 12,
    versions: 3,
    hovered: false,
    plant: {
      id: 1,
      code: '1H0',
    },
    company: {
      id: 1,
      name: 'company 1 long name',
      shortName: 'company short name',
    },
  },
];
