import { CostPlanningItem } from '../../models/costplanningitem.model';

export const costPlanningItems: CostPlanningItem[] = [
  {
    id: 1,
    companyId: 1,
    company: {
      id: 1,
      name: 'company 1 long name',
      shortName: 'company 1',
    },
    costAccTypeId: 2,
    costAccType: {
      id: 2,
      name: 'Budget',
      descr: 'Budget tervezés',
    },
    year: 2021,
    plantId: 1,
    plant: {
      id: 1,
      code: '1H0',
    },
    costCenterId: 1,
    costCenter: {
      id: 1,
      code: '1H3300',
      name: 'Szerelde',
    },
    costGroupId: 2,
    costGroup: {
      id: 2,
      name: 'Anyagköltség',
    },
    itemName: 'karbantartási anyag',
    amountInCurrency: 120000,
    currencyId: 1,
    currency: {
      id: 1,
      isoCode: 'EUR',
    },
    amount: 120000,
    distribution: 0,
    comment: 'some not so long comment',
    costAccountId: 1,
    costAccount: {
      id: 1,
      accountNumber: '60040000',
      name: 'Indirekt anyagköltség',
    },
    p1: 10000,
    p2: 10000,
    p3: 10000,
    p4: 10000,
    p5: 10000,
    p6: 10000,
    p7: 10000,
    p8: 10000,
    p9: 10000,
    p10: 10000,
    p11: 10000,
    p12: 10000,
    task: {
      id: undefined,
      planningItemId: 1,
      taskType: 0,
      taskStatus: 0,
      taskName: 'feladat',
    },
  },
  {
    id: 2,
    companyId: 1,
    company: {
      id: 1,
      name: 'company 1 long name',
      shortName: 'company 1',
    },
    costAccTypeId: 2,
    costAccType: {
      id: 2,
      name: 'Budget',
      descr: 'Budget tervezés',
    },
    year: 2021,
    plantId: 1,
    plant: {
      id: 1,
      code: '1H0',
    },
    costCenterId: 1,
    costCenter: {
      id: 1,
      code: '1H3300',
      name: 'Szerelde',
    },
    costGroupId: 4,
    costGroup: {
      id: 4,
      name: 'Indirekt bérköltség',
    },
    itemName: 'bérköltség',
    amountInCurrency: 240000,
    currencyId: 1,
    currency: {
      id: 1,
      isoCode: 'EUR',
    },
    amount: 240000,
    distribution: 1,
    comment: '',
    costAccountId: 2,
    costAccount: {
      id: 2,
      accountNumber: '62010000',
      name: 'Alapbér',
    },
    p1: 0,
    p2: 0,
    p3: 0,
    p4: 120000,
    p5: 0,
    p6: 0,
    p7: 0,
    p8: 0,
    p9: 0,
    p10: 120000,
    p11: 0,
    p12: 0,
    task: {
      id: undefined,
      planningItemId: 0,
      taskType: 0,
      taskStatus: 0,
      taskName: '',
    },
  },
];
