import { CostAccount } from '../../models/costaccount.model';

export const costAccounts: CostAccount[] = [
  {
    id: 1,
    accountNumber: '60040000',
    name: 'Indirekt anyagköltség',
    fixRate: 0.5,
    varRate: 0.5,
    usedForPersPlanning: false,
    year: 2021,
    yearDate: new Date(2021, 0, 1),
    companyId: 1,
    company: {
      id: 1,
      name: 'company 1 long name',
      shortName: 'company 1',
    },
    costGroupId: 2,
    costGroup: {
      id: 2,
      name: 'Anyagköltség',
      rowIndex: 2,
    },
  },
  {
    id: 2,
    accountNumber: '62010000',
    name: 'Alapbér',
    fixRate: 0.6,
    varRate: 0.4,
    usedForPersPlanning: true,
    year: 2021,
    yearDate: new Date(2021, 0, 1),
    companyId: 1,
    company: {
      id: 1,
      name: 'company 1 long name',
      shortName: 'company 1',
    },
    costGroupId: 4,
    costGroup: {
      id: 4,
      name: 'Indirekt bérköltség',
      rowIndex: 4,
    },
  },
  {
    id: 3,
    accountNumber: '62040000',
    name: 'Bérjárulék',
    fixRate: 0.6,
    varRate: 0.4,
    usedForPersPlanning: true,
    year: 2021,
    yearDate: new Date(2021, 0, 1),
    companyId: 1,
    company: {
      id: 1,
      name: 'company 1 long name',
      shortName: 'company 1',
    },
    costGroupId: 4,
    costGroup: {
      id: 4,
      name: 'Indirekt bérköltség',
      rowIndex: 4,
    },
  },
];
